### ISSUE TITLE
integration w/ node-dev

### ISSUE THREAD

**Issue by kyleroche** [akoenig/express-lingua#15]
Hi, module works great. Very easy to setup. Thanks for the efforts. 

Is there any way to get this to recompile under node-dev module?

**Comment by akoenig** [comment]
Hey kyleroche, glad that you like it. Actually it should work.

Felix Gnass from node-dev says:

> This does not only work for .js files, but also for .json or .node or .coffee files or any other custom extension that has >  been added to require.extensions.

lingua uses JSON in i18n files so that in theory node-dev should recognize if there is a change and restart the app. I will check that out.

**Comment by kyleroche** [comment]
Let me know if I can help debug or anything. It appears that it's not reloading, even when express restarts due to changes in other files.

**Comment by akoenig** [comment]
Okay, after hacking in some other projects I'm back to eliminate some issues in lingua now. Regarding this topic I found out that "node-dev" will only reload modules which will be loaded via "require". Anyway, lingua loads the files via "fs.readFile" which could be replaced by this more elegant way. Elegant, because of the fact that the JSON parsing will also take place in this function. So, it is in the master branch now and will be available in release 0.3.5.
